# 默认配置
profile: dev

# 日志配置
logging:
  level: info
  stdout: true
  file:
    enabled: false
    path: logs/decacan.log
    rotation: daily
    max_files: 7

postgres:
  url: postgres://postgres:postgres@localhost/decacan
  max_connections: 10
  auto_migrate: false
